# Assignments 
# Numpy

Theoretical Questions:

Q1.  Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

Ans. NumPy (Numerical Python) is a fundamental liberary in Python for numerical computations. It provides support for multi-dimensional arrays, mathematical functions, and linear algebra operations, making it essential for scientific computing and data analysis.

Advantage of NumPy:
1. Effcient Dara Structures
   * NumPy arrays (ndarray) are more-efficient and faster than Python lists.
   * They store elements of the same data type in contiguous memory blocks, enabling quick access and modification.
2. Performance Optimization
   * NumPy uses optimized C and Fortan liberaries under the hood.
   * Operations on NumPy arrays are vectorized, meaning they are executed in compiled C code rather than Python loops, leading to signifies speed improvements.
3. Comprehensive Mathematical Functions
   * Supports a wide range of functions: linear algebra, Fourier transforms, random number generation, statistics, and more.
4. Broadcasting
   * Allows arithmetic operations on arrays of different shapes without explicit looping, improving efficiency and readability
5. Interoperability
   * Can interface with C, C++, and Fortran, making it useful for integrating Python with high-performance codebases.
6. Ease of Use with Other Libraries
   * Forms the foundation for Pandas, SciPy, Scikit-Learn, TensorFlow, and Matplotlib, making it integral to data science and machine learning.
  
How NumPy Enhances Python’s Numerical Capabilities:
1. Array-Based Computation
   * Unlike Python lists, NumPy arrays allow element-wise computations in a single operation, reducing execution time.
2. Efficient Memory Usage
   * NumPy arrays consume less memory due to their fixed data type and contiguous memory allocation.
3. Advanced Indexing and Slicing
   * Enables fast retrieval and manipulation of data, supporting boolean indexing, fancy indexing, and slicing.
4. Parallelism and Multi-threading
   * Uses optimized BLAS (Basic Linear Algebra Subprograms) and LAPACK (Linear Algebra Package) libraries to enable multi-threaded computations.
5. Handling Large Datasets
   * Essential for big data and high-performance computing, as it provides fast numerical operations on large datasets.

Q2.  Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other? 

Ans. Comparison of np.mean() and np.average() in NumPy
Both np.mean() and np.average() compute the arithmetic mean of an array, but they differ in how they handle weighting.
* np.mean() calculates the simple arithmetic mean by summing all elements and dividing by the total number of elements. It does not support weighting and treats all elements equally.
* np.average() can compute both a simple mean and a weighted mean. If no weights are provided, it functions like np.mean(). When weights are specified, it calculates the weighted mean, giving different levels of importance to different values.

Key Differences
* np.mean() is used for uniform data where all values contribute equally.
* np.average() is used when certain values should have a greater influence, such as in weighted grading, financial data, or probability distributions.

When to use which:
* Use np.mean() for general statistical calculations where all values have equal significance.
* Use np.average() when weighting is required to emphasize specific data points.

Q3.  Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.

Ans. NumPy provides multiple methods to reverse an array depending on its dimensions and the axis along which the reversal is required.
1. Using Slicin([::-1])
   * This is the simplest and most efficient way to reverse an array.
   * It can be used to reverse a 1D array entirely or reverse specific axes in a 2D array.
   * For a 1D array, applying [::-1] reverses the order of elements.
   * In a 2D array, using [::-1] along the first axis reverses the row order, while [:, ::-1] reverses the column order.
2. Using np.flip()
   * This function provides a generalized way to reverse an array along a specific axis.
   * It allows reversal along multiple dimensions by specifying the axis parameter.
   * For 1D arrays, it functions similarly to slicing.
   * For 2D arrays, np.flip() with axis=0 reverses rows, while axis=1 reverses columns.
   * If no axis is specified, it reverses all dimensions.
3. Using np.flipud() and np.flipr()
   * np.flipud() specifically reverses an array vertically, flipping it upside down.
   * np.fliplr() reverses an array horizontally, flipping it left to right.
   * These functions are useful for structured transformations in image processing or matrix operations.

1D Array Example:

In [6]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)


[5 4 3 2 1]


2D Array Example:

In [8]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_rows = arr2d[::-1]  
print(reversed_rows)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


Q4.  How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.

Ans. The data type of elements in a NumPy array can be determined using the dtype attribute. This provides information about the type of data stored in the array, such as integers, floating-point numbers, or complex numbers.
Importance of Data Types in Memory Management and Performance:
1. Efficient Memory Usage
   * NumPy arrays store elements in contiguous memory blocks, and selecting an appropriate data type helps optimize memory consumption.
   * Using smaller data types, such as int8 instead of int64, can significantly reduce memory usage, especially for large datasets
2. Performance Optimization
   * NumPy operations are highly optimized for specific data types. Choosing the right data type can improve computational efficiency.
   * Smaller data types require fewer CPU cycles for arithmetic operations, leading to faster execution
3. Precision and Accuracy
   * Selecting the correct data type ensures numerical precision.
   * For instance, using float32 instead of float64 may lead to precision loss in scientific computations.
4. Compatibility and Interoperability
   * Ensuring data types match expected formats is important for compatibility with other libraries, databases, and external systems.
   * Incorrect data types can cause unexpected behavior or conversion overhead.
   

Q5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

Ans. An ndarray (N-dimensional array) in NumPy is a multi-dimensional, homogeneous array that stores elements of the same data type in contiguous memory. It serves as the fundamental data structure for numerical computations in Python.

Key Features of ndarray
1. Homogeneous Data Type
    * Unlike Python lists, NumPy arrays store elements of the same type, ensuring consistency and efficiency.
2. Multi-Dimensional Support
   * NumPy arrays can have one or more dimensions (1D, 2D, 3D, etc.), making them suitable for handling matrices and tensors.
3. Efficient Memory Usage
   * Arrays are stored in contiguous memory locations, reducing overhead and enabling fast data access.
4. Vectorized Operations
   * NumPy supports element-wise arithmetic operations without explicit loops, improving performance.
5. Indexing and Slicing
   * Supports advanced indexing, including slicing, boolean indexing, and fancy indexing, for efficient data manipulation.
6. Broadcasting
   * Allows operations between arrays of different shapes without needing explicit reshaping.

Differences Between ndarray and Python Lists:
1. NumPy (ndarray):
   * Data Type - Homogeneous (single type)
   * Performance - Fastest due to vectorization and contiguous memory storage
   * Memory Usage - More efficient
   * Operations - Support element-wise operations
   * Multi-Dimensional Support - support multi-dimensional arrays
3. Python Lists:
   * Data Type - Hetrogeneous (mixed types allowed)
   * Performance - Slower due to dynamic typing and non-contiguous memory
   * Memory Usage - More memory overhead
   * Operations - Requires explicit looping for operations
   * Multi-Dimensional Support - Requires nested lists for multi-dimensional structures

Q6.  Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

Ans. NumPy arrays (ndarray) offer significant performance advantages over Python lists, especially for large-scale numerical computations. These benefits arise from their memory efficiency, vectorized operations, and optimized backend implementations.
1. Memory Efficiency:
   * NumPy arrays consume less memory compared to Python lists because they store elements in contiguous memory blocks.
   * Python lists store references to objects, leading to higher memory overhead.
   * NumPy uses fixed-type storage, reducing unnecessary memory consumption.
2. Faster Computations (Vectorization):
   * NumPy arrays support vectorized operations, where element-wise computations are performed using optimized C-based routines.
   * Python lists require explicit loops for element-wise operations, which are slow due to interpreted execution.
   * Vectorization allows operations to be executed in parallel, utilizing CPU-level optimizations.
3. Optimized Backend (BLAS & LAPACK):
   * NumPy operations leverage highly optimized BLAS (Basic Linear Algebra Subprograms) and LAPACK (Linear Algebra Package) libraries.
   * These libraries enable efficient matrix operations, linear algebra, and numerical computations, significantly boosting performance.
4. Reduced Execution Overhead:
   * Python lists require type checking and dynamic memory allocation for each element, slowing down operations.
   * NumPy arrays are statically typed, eliminating the need for repeated type checking, resulting in faster execution.
5. Broadcasting for Efficient Computation:
   * NumPy supports broadcasting, allowing arithmetic operations on arrays of different shapes without explicit loops.
   * This reduces computational complexity and speeds up large-scale operations.
6. Multi-Core and Parallel Processing:
   * NumPy leverages multi-threading and parallel computing, utilizing modern CPUs efficiently.
   * Large-scale operations automatically run on multiple CPU cores, unlike Python lists, which execute sequentially.

Q7.  Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.

Ans. Both vstack() and hstack() are used to stack NumPy arrays along different axes, but they differ in their behavior:
* vstack()
  -Stacks Along - Vertocal(axis=0)
  -Behaviour - Stacks arrays row-wise (adds rows)
* hstack()
  -Stacks Along - Horizontal (axis=1)
  -Behaviour - Stacks arrays coloumn-wise (adds columns)

Example of vstack():

In [10]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

result = np.vstack((arr1, arr2))
print(result)


[[1 2]
 [3 4]
 [5 6]]


Example of hstack():

In [11]:
arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([[5], [6]])

result = np.hstack((arr3, arr4))
print(result)


[[1 2 5]
 [3 4 6]]


Q8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

Ans. Differences Between fliplr() and flipud() in NumPy
1. fliplr() (Flip Left-Right)
   * Flips the elements of an array horizontally, i.e., it reverses the order of elements within each row (left to right).
   * This operation affects columns (axis 1)
   * It is commonly used when you want to flip or reverse the columns of a matrix.
2. flipud() (Flip Up-Down)
   * Flips the elements of an array vertically, i.e., it reverses the order of the rows (top to bottom).
   * This operation affects rows (axis 0).
   * It is commonly used when you want to flip or reverse the rows of a matrix.

Key Differences:
* fliplr(): Reverses elements along the horizontal axis (columns).
* flipud(): Reverses elements along the vertical axis (rows)
Both functions are useful for different types of transformations, depending on whether the operation needs to be applied across rows or columns of an array.

Q9.  Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

Ans. Functionality of the array_split() Method in NumPy
The array_split() method in NumPy is used to split an array into multiple sub-arrays. It allows an array to be divided into a specified number of equal parts along a given axis. This method is flexible and can handle cases where the number of elements in the array is not evenly divisible by the number of splits.

How It Works:
  * Input: The method takes the input array and a number (or indices) specifying how many parts the array should be split into.
  * Output: It returns a list of sub-arrays

Handling Uneven Splits:
  * When the array cannot be evenly divided by the number of splits, NumPy ensures that the splits are as equal as possible.
  * If there are leftover elements (i.e., the remainder when dividing the total number of elements by the number of splits), NumPy distributes them across the resulting sub-arrays.
  * The earlier sub-arrays will receive one extra element until the remainder is exhausted, and the later sub-arrays will receive fewer elements.

Q10.  Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

Ans. Vectorization in NumPy
Vectorization in NumPy refers to the ability to perform operations on entire arrays, rather than iterating through each element one by one. This approach allows NumPy to apply operations element-wise in compiled, optimized code instead of interpreted Python code, leading to faster execution.

Benefits of Vectorization:
  * Improved performance: Operations are executed more efficiently using low-level, compiled C code.
  * Simplified code: Eliminates the need for explicit loops, making the code cleaner and easier to understand.

Broadcasting in NumPy
Broadcasting is a technique that allows NumPy to perform arithmetic operations on arrays of different shapes without needing explicit reshaping or replication of the arrays. NumPy automatically adjusts the shape of the smaller array to match the larger array's shape in a way that minimizes memory usage.

How Broadcasting Works:
  * When performing operations between arrays of different shapes, NumPy compares their shapes starting from the rightmost dimension. If the dimensions are compatible (either they are the same or one of them is 1), broadcasting occurs.
  * If the arrays' shapes are not compatible, NumPy raises an error.

Contributions to Efficient Array Operations
1. Performance Improvement:
   * Vectorization allows for operations to be carried out without explicit loops, resulting in faster execution.
   * Broadcasting enables operations on arrays of different shapes without duplicating data in memory, thus improving efficiency.
2. Simplification of Code:
   * Both techniques allow for cleaner and more concise code, removing the need for manual iteration or reshaping of arrays
3. Memory Efficiency:
   * Broadcasting reduces memory usage by avoiding the creation of large intermediate arrays and by performing operations directly on the smaller array's shape.
4. Reduction in Python Overhead:
   * With vectorization, the need for Python loops is eliminated, reducing the overhead of interpreted code and significantly enhancing performance.

Practical Questions:

Q1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [12]:
import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100
arr = np.random.randint(1, 101, size=(3, 3))

# Interchange its rows and columns (transpose the array)
transposed_arr = arr.T

# Print the original and transposed arrays
print("Original Array:")
print(arr)
print("\nTransposed Array:")
print(transposed_arr)


Original Array:
[[36 87 29]
 [51 67 82]
 [68 48 89]]

Transposed Array:
[[36 51 68]
 [87 67 48]
 [29 82 89]]


Q2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [13]:
import numpy as np

# Generate a 1D NumPy array with 10 elements
arr_1d = np.arange(1, 11)

# Reshape it into a 2x5 array
arr_2x5 = arr_1d.reshape(2, 5)

# Reshape it into a 5x2 array
arr_5x2 = arr_1d.reshape(5, 2)

# Print the original and reshaped arrays
print("Original 1D Array:")
print(arr_1d)

print("\nReshaped to 2x5 Array:")
print(arr_2x5)

print("\nReshaped to 5x2 Array:")
print(arr_5x2)


Original 1D Array:
[ 1  2  3  4  5  6  7  8  9 10]

Reshaped to 2x5 Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Reshaped to 5x2 Array:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


Q3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [14]:
import numpy as np

# Create a 4x4 NumPy array with random float values
arr_4x4 = np.random.random((4, 4))

# Add a border of zeros around it to create a 6x6 array
arr_with_border = np.pad(arr_4x4, pad_width=1, mode='constant', constant_values=0)

# Print the original and padded arrays
print("Original 4x4 Array:")
print(arr_4x4)

print("\n6x6 Array with Border of Zeros:")
print(arr_with_border)


Original 4x4 Array:
[[0.07857054 0.88480166 0.02576969 0.00562215]
 [0.99966631 0.92784229 0.95166192 0.54408344]
 [0.80499079 0.58855835 0.10754739 0.5203229 ]
 [0.86944453 0.77308444 0.86947547 0.46566993]]

6x6 Array with Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.07857054 0.88480166 0.02576969 0.00562215 0.        ]
 [0.         0.99966631 0.92784229 0.95166192 0.54408344 0.        ]
 [0.         0.80499079 0.58855835 0.10754739 0.5203229  0.        ]
 [0.         0.86944453 0.77308444 0.86947547 0.46566993 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


Q4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [15]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
arr = np.arange(10, 61, 5)

# Print the array
print(arr)


[10 15 20 25 30 35 40 45 50 55 60]


Q5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

In [16]:
import numpy as np

# Create a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase = np.char.upper(arr)
lowercase = np.char.lower(arr)
titlecase = np.char.title(arr)
capitalize = np.char.capitalize(arr)

# Print the transformed arrays
print("Uppercase:", uppercase)
print("Lowercase:", lowercase)
print("Titlecase:", titlecase)
print("Capitalize:", capitalize)


Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Titlecase: ['Python' 'Numpy' 'Pandas']
Capitalize: ['Python' 'Numpy' 'Pandas']


Q6. Generate a NumPy array of words. Insert a space between each character of every word in the array

In [17]:
import numpy as np

# Create a NumPy array of words
words_arr = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word in the array
words_with_spaces = np.char.join(' ', words_arr)

# Print the resulting array
print(words_with_spaces)


['p y t h o n' 'n u m p y' 'p a n d a s']


Q7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [18]:
import numpy as np

# Create two 2D NumPy arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Perform element-wise addition, subtraction, multiplication, and division
addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2

# Print the results
print("Addition:")
print(addition)
print("\nSubtraction:")
print(subtraction)
print("\nMultiplication:")
print(multiplication)
print("\nDivision:")
print(division)


Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Subtraction:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Division:
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


Q8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [19]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)

# Print the identity matrix and the diagonal elements
print("Identity Matrix:")
print(identity_matrix)

print("\nDiagonal Elements:")
print(diagonal_elements)


Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


Q9.  Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.

In [20]:
import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
arr = np.random.randint(0, 1001, size=100)

# Function to check if a number is prime
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            return False
    return True

# Find all prime numbers in the array
prime_numbers = [num for num in arr if is_prime(num)]

# Print the array and the prime numbers
print("Array of Random Integers:")
print(arr)

print("\nPrime Numbers in the Array:")
print(prime_numbers)


Array of Random Integers:
[ 88 462 529 876  70 408 913 923 500 565 349 742 721 450 627 446 148 987
 547 351 135 613 912 269 576 247 218 651 338 704 611 637 364 137 581 325
 832 718 149 694 457 494  88 460 984 765 442  66 418 262 134 794 722 603
 127 418 228 972  49 297 199 543 672 550 130 269 329 545  91 528 421 510
 409  82 122 472 292 130 300 480 737 785 235 218 829 900 766 570  78  97
 319 208 705 667 635 605 867 272 554 810]

Prime Numbers in the Array:
[np.int32(349), np.int32(547), np.int32(613), np.int32(269), np.int32(137), np.int32(149), np.int32(457), np.int32(127), np.int32(199), np.int32(269), np.int32(421), np.int32(409), np.int32(829), np.int32(97)]


Q10.  Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.

In [25]:
import numpy as np

# Generate a NumPy array representing daily temperatures for a month (30 days)
daily_temperatures = np.random.uniform(15, 35, size=30)

# Calculate weekly averages by splitting the array into 4 weeks (5 days in each week)
weekly_averages = daily_temperatures.reshape(5, 6)[:, :5].mean(axis=1)

# Print the daily temperatures and weekly averages
print("Daily Temperatures for the Month:")
print(daily_temperatures)

print("\nWeekly Averages:")
print(weekly_averages)



Daily Temperatures for the Month:
[30.7824224  34.61666846 26.11298103 21.55062196 16.82879647 28.71987721
 32.68350414 24.23117129 31.37785408 22.77561473 17.20214447 26.89521927
 19.40133671 17.95275394 25.32267184 18.17568591 21.41090684 34.18501514
 30.73633979 18.34155575 31.17323864 15.99400933 20.56720632 16.35235964
 34.7906102  20.69307206 24.72198942 19.41662773 18.1934261  20.55701008]

Weekly Averages:
[25.97829806 25.65405774 20.45267105 23.36246997 23.5631451 ]
